기능 일부 추가 했습니다 수정 계속 이어가겠습니다.
SimonDevelope/airbnb_refactory pull request #5
Opened 2021-07-11 15:00 UTC by SimonDevelope

2021-07-12 15:54 UTC, lcpnine requested changes
전체적인 문제점 몇가지만 적겠습니다.
1. state는 컴포넌트 렌더링을 위한 상태를 저장하는 곳이지 컴포넌트를 저장하는 곳이 아닙니다. 상태에 따라 컴포넌트를 렌더링하고 싶을떄는 삼항연산자를 사용해 렌더링하도록 합니다.
2. 변수명을 보면 어떤 역할을 하는지 전혀 알 수있습니다. 현재 코드로 과연 한달뒤에 코드를 보더라도 이게 어떤 역할을 하는 코드인지 알 수 있을까요? 변수명 짓는게 가장 어렵다고들 하죠. 좋은 변수명 고민을 항상 해보도록 합니다.

2021-07-12 15:54 UTC, lcpnine commented on src/Components/MainHeader/MiddleMenu/Function/Calender/Calender.js
> +            <button className="calender-switch-btn-common-attr-A">
```suggestion
            <button className="calender-switch-btn-common-attr-어떤기능">
```
이런식으로 직접 기능을 명시하는 것이 A, B라고 하는 것보다 좋을 것 같아요

2021-07-12 15:54 UTC, lcpnine commented on src/Components/MainHeader/MiddleMenu/Function/NOP/Nop.js
> +    setNumber((prevNumber) => prevNumber + 1);
```suggestion
    setNumber(prevNumber => prevNumber + 1);
```

```suggestion
    setNumber(number + 1);
```
의 차이를 명확히 이해할 수 있어야 합니다

2021-07-12 15:54 UTC, lcpnine commented on src/Components/MainHeader/MiddleMenu/MiddleMenu.js
> +  const [state, setState] = useState(() => {
State는 컴포넌트를 저장하기 위한 곳이 아닙니다. 상태는 컴포넌트가 렌더링 할 때 필요한 정보들을 저장하는 곳이지 컴포넌트가 저장되는 곳이 아닙니다.
또한 상태 이름을 state로 짓는 것은 정말 좋지 않은 명명법입니다

2021-07-12 15:54 UTC, lcpnine commented on src/Components/MainHeader/MiddleMenu/MiddleMenu.js
> +              <div>{state}</div>
위에서 이부분을 상황에 따라 다른 컴포넌트를 하고 싶었군요
state를 boolean으로 설정하고 삼항연산자를 사용해서 상태에 따른 컴포넌트를 나타낼 수 있습니다.
예를들어 showLodge란 state가 true일때 `<Lodge />`, false일 떄 `<Experience />`를 나타내고 싶다면
```suggestion
              {` showLodge ? <Lodge /> : <Experience />}
```
로 나타낼 수 있습니다

2021-07-12 15:54 UTC, lcpnine commented on src/Components/MainHeader/MiddleMenu/SearchBar/SearchBar.js
> +    setSearch((search) => !search);
`setState(prevValue => prevValue + 1)`은 동기적으로 상태값을 업데이트 하기에 자주 사용이 권장되는 방법은 아닙니다. `setState(nextValue)` 방식을 최대한 사용하고 동기적인 업데이트는 꼭 필요한 때만 사용하도록 하세요.

2021-07-12 15:54 UTC, lcpnine commented on src/Components/MainHeader/MiddleMenu/SearchBar/SearchBar.js
> +  const [search, setSearch] = useState(false);
search는 컴포넌트를 보여주기 위한 변수명이니 `search`보다는 `showSearch`를 사용하여 좀 더 명확하게 어떤 역할을 하는 상태값인지 보여주는 것이 좋습니다.

2021-07-12 15:54 UTC, lcpnine commented on src/Components/MainHeader/MiddleMenu/SearchBar/SearchBar.js
> +  const [add, setAdd] = useState(false);
add 역시 인원수 더하기에 관련한 버튼을 보여주는 것이라면 `showAddBtn`과 같은 상태명을 사용하는 것이 좋습니다

2021-07-12 15:54 UTC, lcpnine commented on src/Components/MainHeader/MiddleMenu/SearchBar/SearchBar.js
> +  const onButton = () => {
버튼이 하나만 있더라도 onButton으로 함수명을 지으면 좋지 않습니다. 정확히 어떤 일을 하는 것인지 명시하도록 하세요

2021-07-12 15:54 UTC, lcpnine commented on src/Components/MainHeader/MiddleMenu/SearchBar/SearchBar.js
> +  const [calender, setCalender] = useState(false);
위와 같습니다

2021-07-12 15:54 UTC, lcpnine commented on src/Components/MainHeader/MiddleMenu/SearchBar/SearchBar.js
> +    window.addEventListener('mousedown', closedModal);
보통은 window에 이벤트리스너를 추가하지 않고 document에 추가합니다
```suggestion
    document.addEventListener('mousedown', closedModal);
```
가끔 window 객체에 이벤트 리스너를 달아야 하는 경우가 있는데요, 현재 상황에서는 모르셔도 괜찮을 것 같습니다.

2021-07-12 15:54 UTC, lcpnine commented on src/Components/MainHeader/MiddleMenu/SearchBar/SearchBar.js
> +      window.removeEventListener('mousedown', closedModal);
위와 마찬가지입니다.

2021-07-12 15:54 UTC, lcpnine commented on src/Components/MainHeader/MiddleMenu/SearchBar/SearchBar.js
> +      <div className="Total-outter-wrapper">
여전히 대문자 className들이 사용되고 있습니다.

2021-07-12 15:54 UTC, lcpnine commented on src/Components/MainHeader/MiddleMenu/SearchBar/SearchBar.js
> +              <div className="Inner-contents-attr" onClick={onToggle}>
`onToggle`역시 무엇을 Toggle하는지 명확히 알려주세요.

2021-07-12 15:54 UTC, lcpnine commented on src/Components/MainHeader/MiddleMenu/SearchBar/SearchBar.js
> +                    <svg
svg를 사용한 부분은 따로 컴포넌트화 할 수 있을 것 같은데요

2021-07-12 15:54 UTC, lcpnine commented on src/Components/MainHeader/MiddleMenu/SearchBar/SearchBar.js
> +                <svg
위와 마찬가지입니다.

2021-07-12 15:54 UTC, lcpnine commented on src/Components/MainHeader/MyMenu/MyMenu.js
> +    window.addEventListener('mousedown', CloseMenu);
window관련은 더이상 남기지 않겠습니다.

2021-07-12 15:54 UTC, lcpnine commented on src/Components/MainHeader/MyMenu/MyMenu.js
> +  const Elementml = useRef();
Elementml은 무슨 의미일까요?

2021-07-12 15:54 UTC, lcpnine commented on src/Components/MainHeader/MyMenu/MyMenu.js
> +                <svg
svg도 별도로 남기지 않겠습니다. 충분히 컴포넌트화 할 수 있을 것 같네요

2021-08-01 09:32 UTC, SimonDevelope commented on server/server.js
> +app.get("/tobelive", (req, res) => {
여기서 보자면 경로를 '/'와 '/tobelive', '/lookforexperi'라는 세 가지의 경로를 통해서 각자의 테이블 데이터 값을 가지고 왔습니다.

제가 궁금한 것은 처음에 '/'라는 경로로 서로 다른 테이블의 데이터 값을 "SELECT * FROM 테이블명"으로 확인해보는 과정에서 데이터가 확인되지 않아서 서로 다른 경로를 주고 실행해본 결과 서로 다른 테이블 값을 잘 가지고 오는 것을 볼 수 있었습니다.

그래서 보시는 코드와 같이 정보를 가지고 오게 되었는데 이렇게 하는 것이 맞는지 아니면 다른 방법을 이용해야 하는지에 대해서 궁금합니다.

2021-08-01 10:04 UTC, lcpnine commented on server/server.js
> +app.get("/tobelive", (req, res) => {
`이렇게 하는 것이 맞는지 아니면 다른 방법을 이용해야 하는지에 대해서 궁금합니다.`가 어떤 의미일까요? 다른 테이블의 값을 가져오기 위해서는 다른 rest api endpoint를 사용해야 한다는 말씀이실까요?

또산 서버 작업은 제가 리뷰를 남겼던 PR과 다른 작업인데 merge하고 git cherrypick을 이용해 새로운 브랜치를 파서 코드 리뷰를 신청하셨으면 더 좋았을 것 같습니다. 리뷰를 남기고 merge 해 놓을테니 앞으로는 새로운 리뷰를 받을때는 새로운 브랜치를 파서 PR을 신청해주시기 바랍니다.

2021-08-01 10:04 UTC, merged